### ISSUE TITLE
GitHub Link funktioniert nicht

### ISSUE THREAD

**Issue by Pauletta** [Jugendhackt/Handbuch-Jugend-Hackathons#13]
Das GitHub Icon oben verlinkt auf handbuch.jugendhackt.de nicht auf des Repo hier.

**Comment by niccokunzmann** [comment]
Dieser Link hat mit zum Repository geführt: 
![image](https://cloud.githubusercontent.com/assets/564768/22078179/7ef09262-ddb7-11e6-94bb-05cdb85b83d2.png)

**Comment by joliyea** [comment]
GitHub Icon verlinkt korrekt auf dieses Repo.
