### ISSUE TITLE
Translate to Dutch

### ISSUE THREAD

**Issue by milovanderlinden** [Jugendhackt/Handbuch-Jugend-Hackathons#3]
Hello @rhotep we would love to translate das Handbuch to dutch. What filestructure do you suggest; should we write everything in /nl or do you have another method in mind?

**Comment by rhotep** [comment]
Nice! :) I haven't thought about multi language support yet. Everything you put in /_chapter will be rendered as a chapter regardless of any subdirectory structure in /_chapter. Just make sure chapter files have a yaml header like this:
<pre>
---
title: "Some title"
number: "1.3.2.9"
---
</pre>

Chapter numbers can have up to three dots.

So for now you could put everything in _chapters/nl and it will render in between the german chapters or put it anywhere outside of _chapters (e.g. /nl) and it wont render at all.

In the meantime I will think of some way to support  multiple languages at once and then come back to you :)

**Comment by rhotep** [comment]
I setup support for a transalted book. Take a look at the [READ.ME](https://github.com/Jugendhackt/Handbuch-Jugend-Hackathons/blob/master/README.md)

**Comment by milovanderlinden** [comment]
Perfect! I am going to commit to that. Thank you!
