### ISSUE TITLE
"Anhang"

### ISSUE THREAD

**Issue by niccokunzmann** [Jugendhackt/Handbuch-Jugend-Hackathons#5]
Hallo, 

im Text ist mehrfach vom Anhnag die Rede. Ich kann ihn aber nicht finden. Kann der Anhang verlinkt werden?

Viele Grüße, 
Nicco

**Comment by Pauletta** [comment]
Hi Nicco,
Das ist der Hier: https://github.com/Jugendhackt/Handbuch-Jugend-Hackathons/tree/master/appendix
Aber ja, du hast Recht, den sollte man verlinken :)
LG, Paula

**Comment by rhotep** [comment]
Jetzt gibt es ein Kapitel "Anhang" :)
